theme: jekyll-theme-primer
title: "AQ&U Project Information"
description: "You will find details about the Project CPS: Synergy: A Layered Framework of Sensors, Models, Land-Use Information and Citizens for Understanding Air Quality in Urban Environments"
